# Makefile - Lab 2 Queue and Stack directory

all:	Queue-ArrayVersion1.exe \
		Queue-ArrayVersion2.exe \
		Queue-ArrayVersion3.exe \
		Queue-LinkListVersion.exe \
		Stack-ArrayVersion00.exe \
		Stack-ArrayVersion01.exe \
		Stack-BracketChecker.exe \
		Stack-LinkListVersion00.exe \
		Stack-MultiInstance.exe \
		Stack-Strings.exe \
		Stack-UsingQ.exe

clean:
	del *.exe
	del *.obj
	del *.map


Queue-ArrayVersion1.exe:		Queue-ArrayVersion1.c

Queue-ArrayVersion2.exe:		Queue-ArrayVersion2.c

Queue-ArrayVersion3.exe:		Queue-ArrayVersion3.c

Queue-LinkListVersion.exe:		Queue-LinkListVersion.c

Stack-ArrayVersion00.exe:		Stack-ArrayVersion00.c

Stack-ArrayVersion01.exe:		Stack-ArrayVersion01.c

Stack-BracketChecker.exe:		Stack-BracketChecker.c

Stack-LinkListVersion00.exe:	Stack-LinkListVersion00.c

Stack-MultiInstance.exe:		Stack-MultiInstance.c

Stack-Strings.exe:				Stack-Strings.c

Stack-UsingQ.exe:				Stack-UsingQ.c
