all:	L5_testsort.exe makedata.exe makedata2.exe

clean:
		del	*.obj
		del	*.exe
		del	*.bak
		del	*.lst

L5_TESTSORT.exe:	L5_TESTSORT.obj

L5_TESTSORT.obj:	L5_BCKTSORT.C L5_BUBBLESORT.c L5_HEAPSORT.C L5_INSTSORT.C \
					L5_MERGESORT.C L5_QUICKSORT.C L5_RADXSORT.C L5_SELSORT.C \
					L5_SHELLSORT.c L5_TESTSORT.c L5_UTILITYCODE.c


